### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by GarreauArthur** [GarreauArthur/webProjetInfra#2]
* [x] faire reservation.php
* [x] faire attention XSS dans chambres.php
* [x] faire vérification dateDebut < dateFin
* [x] améliorer style CSS
* [x] trouver une meilleure solution que msg=error
* [x] ajouter un récap dans reservation.php
* [x] ajouter un récap dans confirmation.php
* [x] vérifier que personne n'a réservé la chambre entre temps (dans confirmation.php)
* [ ] créer un système de compte utilisateur
* [x] faire page pour annuler la réservation

**Comment by AdrienIzy** [comment]
* [x] empêcher la duplication de client et de réservation
* [x] vérifier les champs du formulaire "Informations client"
* [ ] envoyer confirmation par mail lors d'une réservation
* [x] changer message d’erreur (pas de chambre disponibles)
* [x] calculer le prix total en fonction du nombre de nuits réservées
* [x] vérifier dates > auj
* [ ] bouton retour
* [ ] présentation hôtel dans choix dates
* [ ] design annuler

**Comment by GarreauArthur** [comment]
Créer un remote sur la VM pour continuer à travailler tout en déployant : 

* Sur machine locale (dans webProjetInfra) :
    * `git pull origin master`
    * `cd ..`
    * `scp -rp webProjetInfra 192.168.4.142:/var/www/webProjetInfra`
    * `git remote add vm ssh://root@192.168.4.142:/var/www/webProjetInfra`

Après ça, pour pull :

    git pull vm master

pour push :

    git push vm master
